"""empty message

Revision ID: 182ca077c5b4
Revises: 7600a65ea7ce
Create Date: 2024-09-01 10:32:52.326723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '182ca077c5b4'
down_revision = '7600a65ea7ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('genres')

    # ### end Alembic commands ###
